*** Settings ***
Resource    ../../../flow/administracao_medicamento/create_administracao_medicamento/create_administracao_medicamento_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
ADMINISTRACAO MEDICAMENTO - CREATE - POST
    [Documentation]    Test scenario for POST /api/v1/administracao-medicamento/ on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Administracao Medicamento - Create - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

