*** Settings ***
Resource    ../../../flow/solicitacao_regulacao/complemento_solicitacao_regulacao/complemento_solicitacao_regulacao_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
SOLICITACAO REGULACAO - COMPLEMENTO - POST
    [Documentation]    Test scenario for POST /api/v1/solicitacao-regulacao/{uuid}/complemento on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Solicitacao Regulacao - Complemento - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
