*** Settings ***
Resource    ../../../flow/perfil_administrativo/update_perfil_administrativo/update_perfil_administrativo_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PERFIL ADMINISTRATIVO - UPDATE - PATCH
    [Documentation]    Test scenario for updating a Perfil Administrativo (PATCH /api/v1/perfil-administrativo/{uuid})
    ...    on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Perfil Administrativo - Update - PATCH - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
