*** Settings ***
Resource    ../../../flow/movimentacao_farmacia/create_movimentacao_farmacia/create_movimentacao_farmacia_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
MOVIMENTACAO FARMACIA - CREATE - POST
    [Documentation]    Test scenario for registering a stock movement (POST /api/v1/movimentacao-farmacia/) on the
    ...    Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Movimentacao Farmacia - Create - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
