*** Settings ***
Resource    ../../../flow/perfil_administrativo/create_perfil_administrativo/create_perfil_administrativo_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PERFIL ADMINISTRATIVO - CREATE - POST
    [Documentation]    Test scenario for creating a Perfil Administrativo (POST /api/v1/perfil-administrativo/)
    ...    on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Perfil Administrativo - Create - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
