*** Settings ***
Resource    ../../../flow/capacidade_administrativa/update_capacidade_administrativa/update_capacidade_administrativa_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
CAPACIDADE ADMINISTRATIVA - UPDATE - PATCH
    [Documentation]    Test scenario for updating a Capacidade Administrativa
    ...    (PATCH /api/v1/capacidade-administrativa/{uuid}) on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Capacidade Administrativa - Update - PATCH - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
