*** Settings ***
Resource    ../../../flow/estadual/desabilitar_estadual/desabilitar_estadual_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
ESTADUAL - DESABILITAR - DELETE
    [Documentation]    Test scenario for enabling/disabling an Estadual unit
    ...    (DELETE /api/v1/estadual/des-habilitar/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Estadual - Desabilitar - DELETE - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
