*** Settings ***
Resource    ../../../flow/processo_administrativo/update_processo_administrativo/update_processo_administrativo_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PROCESSO ADMINISTRATIVO - UPDATE - PATCH
    [Documentation]    Test scenario for updating a Processo Administrativo
    ...    (PATCH /api/v1/processo-administrativo/{uuid}) on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Processo Administrativo - Update - PATCH - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
