*** Settings ***
Resource    ../../../flow/transferencia_farmacia/cancelamento_transferencia_farmacia/cancelamento_transferencia_farmacia_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
TRANSFERENCIA FARMACIA - CANCELAMENTO - POST
    [Documentation]    Test scenario for POST /api/v1/transferencia-farmacia/{uuid}/cancelamento on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Transferencia Farmacia - Cancelamento - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

