*** Settings ***
# FEDERAL
Resource    ../../data_driven/federal/federal_driven.resource
# REGIONAL
Resource    ../../data_driven/regional/regional_driven.resource
# ESTADUAL
Resource    ../../data_driven/estadual/estadual_driven.resource
# MUNICIPAL
Resource    ../../data_driven/municipal/municipal_driven.resource
# UNIDADE SAUDE
Resource    ../../data_driven/unidade_saude/unidade_saude_driven.resource
# PROFISSIONAL
Resource    ../../data_driven/profissional/profissional_driven.resource
