*** Settings ***
Resource    ../../../flow/transferencia_farmacia/create_transferencia_farmacia/create_transferencia_farmacia_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
TRANSFERENCIA FARMACIA - CREATE - POST
    [Documentation]    Test scenario for transferring stock between units (POST /api/v1/transferencia-farmacia/) on
    ...    the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Transferencia Farmacia - Create - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
