*** Settings ***
Resource    ../../../flow/regional/desabilitar_regional/desabilitar_regional_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
REGIONAL - DESABILITAR - DELETE
    [Documentation]    Test scenario for enabling/disabling a Regional unit
    ...    (DELETE /api/v1/regional/des-habilitar/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Regional - Desabilitar - DELETE - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
