*** Settings ***
Resource    ../../../flow/unidade_saude/get_unidade_saude_by_nome/get_unidade_saude_by_nome_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
UNIDADE SAUDE - GET BY NOME - GET
    [Documentation]    Test scenario for fetching a Unidade de Saúde unit by nome
    ...    (GET /api/v1/unidade-saude/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Unidade Saude - Get By Nome - GET - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
