*** Settings ***
Resource    ../../../flow/capacidade_administrativa/get_capacidade_administrativa_by_id/get_capacidade_administrativa_by_id_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
CAPACIDADE ADMINISTRATIVA - GET BY ID - GET
    [Documentation]    Test scenario for fetching a Capacidade Administrativa by id
    ...    (GET /api/v1/capacidade-administrativa/{uuid}) on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Capacidade Administrativa - Get By Id - GET - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
