*** Settings ***
Resource    ../../../flow/federal/desabilitar_federal/desabilitar_federal_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
FEDERAL - DESABILITAR - DELETE
    [Documentation]    Test scenario for enabling/disabling a Federal unit
    ...    (DELETE /api/v1/federal/des-habilitar/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Federal - Desabilitar - DELETE - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
