*** Settings ***
Resource    ../../../flow/perfil_administrativo/get_perfil_administrativo_by_id/get_perfil_administrativo_by_id_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PERFIL ADMINISTRATIVO - GET BY ID - GET
    [Documentation]    Test scenario for fetching a Perfil Administrativo by id
    ...    (GET /api/v1/perfil-administrativo/{uuid}) on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Perfil Administrativo - Get By Id - GET - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
