apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mais-saude-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dufelizardo/mais_saude_publica.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: mais-saude-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
