*** Settings ***
Resource    ../../../flow/capacidade_administrativa/create_capacidade_administrativa/create_capacidade_administrativa_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
CAPACIDADE ADMINISTRATIVA - CREATE - POST
    [Documentation]    Test scenario for creating a Capacidade Administrativa (POST /api/v1/capacidade-administrativa/)
    ...    on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Capacidade Administrativa - Create - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
