*** Settings ***
Resource    ../../../flow/processo_administrativo/get_processo_administrativo_by_id/get_processo_administrativo_by_id_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PROCESSO ADMINISTRATIVO - GET BY ID - GET
    [Documentation]    Test scenario for fetching a Processo Administrativo by id
    ...    (GET /api/v1/processo-administrativo/{uuid}) on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Processo Administrativo - Get By Id - GET - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
