*** Settings ***
Resource    ../../../flow/solicitacao_regulacao/agendamento_solicitacao_regulacao/agendamento_solicitacao_regulacao_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
SOLICITACAO REGULACAO - AGENDAMENTO - POST
    [Documentation]    Test scenario for POST /api/v1/solicitacao-regulacao/{uuid}/agendamento on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Solicitacao Regulacao - Agendamento - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
