*** Settings ***
Resource    ../../../flow/regional/update_horario_atendimento_regional/update_horario_atendimento_regional_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
REGIONAL - UPDATE HORARIO DE ATENDIMENTO - PATCH
    [Documentation]    Test scenario for updating a Regional unit's horario de atendimento
    ...    (PATCH /api/v1/regional/horario-de-atendimento/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Regional - Update Horario De Atendimento - PATCH - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
