*** Settings ***
Resource    ../../../flow/municipal/update_horario_funcionamento_municipal/update_horario_funcionamento_municipal_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
MUNICIPAL - UPDATE HORARIO DE FUNCIONAMENTO - PATCH
    [Documentation]    Test scenario for updating a Municipal unit's horario de funcionamento
    ...    (PATCH /api/v1/municipal/horario-de-funcionamento/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Municipal - Update Horario De Funcionamento - PATCH - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
