*** Settings ***
Resource    ../../../flow/procedimento_regulado/create_procedimento_regulado/create_procedimento_regulado_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PROCEDIMENTO REGULADO - CREATE - POST
    [Documentation]    Test scenario for POST /api/v1/procedimento-regulado/ on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Procedimento Regulado - Create - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
