*** Settings ***
Resource    ../../../flow/municipal/update_horario_atendimento_municipal/update_horario_atendimento_municipal_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
MUNICIPAL - UPDATE HORARIO DE ATENDIMENTO - PATCH
    [Documentation]    Test scenario for updating a Municipal unit's horario de atendimento
    ...    (PATCH /api/v1/municipal/horario-de-atendimento/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Municipal - Update Horario De Atendimento - PATCH - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
