*** Settings ***
Resource    ../../../flow/regional/update_horario_funcionamento_regional/update_horario_funcionamento_regional_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
REGIONAL - UPDATE HORARIO DE FUNCIONAMENTO - PATCH
    [Documentation]    Test scenario for updating a Regional unit's horario de funcionamento
    ...    (PATCH /api/v1/regional/horario-de-funcionamento/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Regional - Update Horario De Funcionamento - PATCH - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
