*** Settings ***
Resource    ../../../flow/transferencia_farmacia/recebimento_transferencia_farmacia/recebimento_transferencia_farmacia_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
TRANSFERENCIA FARMACIA - RECEBIMENTO - POST
    [Documentation]    Test scenario for POST /api/v1/transferencia-farmacia/{uuid}/recebimento on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Transferencia Farmacia - Recebimento - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

