*** Settings ***
Resource    ../../../flow/administracao_medicamento/get_administracao_medicamento_by_id/get_administracao_medicamento_by_id_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
ADMINISTRACAO MEDICAMENTO - GET BY ID - GET
    [Documentation]    Test scenario for GET /api/v1/administracao-medicamento/{uuid} on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Administracao Medicamento - Get By Id - GET - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

