*** Settings ***
Resource    ../../../flow/procedimento/retificar_procedimento/retificar_procedimento_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PROCEDIMENTO - RETIFICACAO - POST
    [Documentation]    Test scenario for retifying a Procedimento (POST /api/v1/procedimento/{uuid}/retificacao) on the Mais Saúde
    ...    Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Procedimento - Retificacao - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

