*** Settings ***
Resource    ../../../flow/municipal/desabilitar_municipal/desabilitar_municipal_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
MUNICIPAL - DESABILITAR - DELETE
    [Documentation]    Test scenario for enabling/disabling a Municipal unit
    ...    (DELETE /api/v1/municipal/des-habilitar/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Municipal - Desabilitar - DELETE - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
