*** Settings ***
Resource    ../../../flow/administracao_medicamento/retificar_administracao_medicamento/retificar_administracao_medicamento_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
ADMINISTRACAO MEDICAMENTO - RETIFICACAO - POST
    [Documentation]    Test scenario for POST /api/v1/administracao-medicamento/{uuid}/retificacao on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Administracao Medicamento - Retificacao - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

