*** Settings ***
Resource    ../../../flow/solicitacao_regulacao/realizacao_solicitacao_regulacao/realizacao_solicitacao_regulacao_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
SOLICITACAO REGULACAO - REALIZACAO - POST
    [Documentation]    Test scenario for POST /api/v1/solicitacao-regulacao/{uuid}/realizacao on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Solicitacao Regulacao - Realizacao - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
