*** Settings ***
Resource    ../../../flow/processo_administrativo/create_processo_administrativo/create_processo_administrativo_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PROCESSO ADMINISTRATIVO - CREATE - POST
    [Documentation]    Test scenario for creating a Processo Administrativo (POST /api/v1/processo-administrativo/)
    ...    on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Processo Administrativo - Create - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
