*** Settings ***
Resource    ../../../flow/estadual/update_horario_atendimento_estadual/update_horario_atendimento_estadual_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
ESTADUAL - UPDATE HORARIO DE ATENDIMENTO - PATCH
    [Documentation]    Test scenario for updating an Estadual unit's horario de atendimento
    ...    (PATCH /api/v1/estadual/horario-de-atendimento/{nome}) on the Mais Saúde Pública API.
    [Arguments]    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Estadual - Update Horario De Atendimento - PATCH - By HTTP Status Code    ${meuNome}    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
