*** Settings ***
Resource    ../../../flow/procedimento/status_procedimento/status_procedimento_flow.resource
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Comments ***
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
*** Keywords ***
PROCEDIMENTO - STATUS - POST
    [Documentation]    Test scenario for registering the outcome of a scheduled Procedimento (POST /api/v1/procedimento/{uuid}/status)
    ...    on the Mais Saúde Pública API.
    [Arguments]    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
    Procedimento - Status - POST - By HTTP Status Code    ${meuHTTP}
    # ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
# ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

