*** Settings ***
# COMMON
Resource    ../../schema/common/common_schema.resource
# FEDERAL
Resource    ../../schema/federal/federal_schema.resource
# REGIONAL
Resource    ../../schema/regional/regional_schema.resource
# ESTADUAL
Resource    ../../schema/estadual/estadual_schema.resource
# MUNICIPAL
Resource    ../../schema/municipal/municipal_schema.resource
# UNIDADE SAUDE
Resource    ../../schema/unidade_saude/unidade_saude_schema.resource
# PROFISSIONAL
Resource    ../../schema/profissional/profissional_schema.resource
# SETOR
Resource    ../../schema/setor/setor_schema.resource
# CAPACIDADE ADMINISTRATIVA
Resource    ../../schema/capacidade_administrativa/capacidade_administrativa_schema.resource
