*** Settings ***
# COMMON
Resource    ../../schema/common/common_schema.resource
# FEDERAL
Resource    ../../schema/federal/federal_schema.resource
# REGIONAL
Resource    ../../schema/regional/regional_schema.resource
# ESTADUAL
Resource    ../../schema/estadual/estadual_schema.resource
# MUNICIPAL
Resource    ../../schema/municipal/municipal_schema.resource
# UNIDADE SAUDE
Resource    ../../schema/unidade_saude/unidade_saude_schema.resource
# PROFISSIONAL
Resource    ../../schema/profissional/profissional_schema.resource
# SETOR
Resource    ../../schema/setor/setor_schema.resource
# CAPACIDADE ADMINISTRATIVA
Resource    ../../schema/capacidade_administrativa/capacidade_administrativa_schema.resource
# PERFIL ADMINISTRATIVO
Resource    ../../schema/perfil_administrativo/perfil_administrativo_schema.resource
# PERFIL POR TIPO UNIDADE
Resource    ../../schema/perfil_por_tipo_unidade/perfil_por_tipo_unidade_schema.resource
# PROCESSO ADMINISTRATIVO
Resource    ../../schema/processo_administrativo/processo_administrativo_schema.resource
# RESPONSABILIDADE ADMINISTRATIVA
Resource    ../../schema/responsabilidade_administrativa/responsabilidade_administrativa_schema.resource
# NECESSIDADE DE PESSOAL
Resource    ../../schema/necessidade_de_pessoal/necessidade_de_pessoal_schema.resource
# PACIENTE
Resource    ../../schema/paciente/paciente_schema.resource
# ATENDIMENTO
Resource    ../../schema/atendimento/atendimento_schema.resource
# AGENDAMENTO
Resource    ../../schema/agendamento/agendamento_schema.resource
# CONSULTA
Resource    ../../schema/consulta/consulta_schema.resource
